name: Build ImpressiveTitle Dependencies
on:
  push:
    branches:
    - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v6
    - name: Install Build Dependencies
      run: |
        sudo apt install xorg-dev libgl-dev libglu-dev libpulse-dev
        tar -xf Cg-3.1_April2012_x86_64.tgz
        sudo cp -r usr/include/* /usr/include/
        sudo cp -r usr/lib64/* /usr/lib64/
        ls /usr/include/
        ls /usr/lib64/
